### POST add a user
POST http://127.0.0.1:8080/api.php/users
Accept: application/json
Content-Type: application/json

{
  "user":"root",
  "password": "supagudVHS"
}

### POST add a user
POST http://127.0.0.1:8080/api.php/auth/register
Accept: application/json
Content-Type: application/json

{
  "user":"root",
  "password": "supagudVHS"
}

### POST login a user
POST http://127.0.0.1:8080/api.php/auth/login
Accept: application/json
Content-Type: application/json

{
  "username":"root",
  "password": "supagudVHS"
}

### GET films
GET http://127.0.0.1:8080/api.php/films
Accept: application/json

### GET by film title
GET http://127.0.0.1:8080/api.php/films/title/Casablanca
Accept: application/json

### GET by actor fullname
GET http://127.0.0.1:8080/api.php/films/actor/Robert Redford
Accept: application/json

### POST add a film
POST http://127.0.0.1:8080/api.php/films
Accept: application/json
Content-Type: application/json

{
  "title":"Percy Jackson and the Olympians",
  "format": "VHS",
  "release_year": 2023,
  "actors": "Walker Scobell, Leah Jeffries,Aryan Simhadri"
}

### DELETE by film id
DELETE http://127.0.0.1:8080/api.php/films/55
Accept: application/json
